on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  apiTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      - name: Build and run Web API + getting process ID for shutting down later
        run: cd api && dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
        env:
          dbconnectionstring: ${{secrets.PGCONN}}

      - name: Run tests once API is running (sleep interval set to 30 seconds)
        run: cd TestProject && sleep 30 && dotnet test --filter FullyQualifiedName~TestProject.ApiTests

        env:
          dbconnectionstring: ${{secrets.PGCONN}}
          
      - name: Shutdown Web API once the tests are done running
        run: if kill -0 $API_PID > /dev/null 2>&1; then kill $API_PID; fi
