on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      #- name: Install Angular program dependencies, Angular global CLI + ng build
       # run: cd api/Front-Drip && npm i -g @angular/cli && npm i && ng build -c="development"

      - name: Build and run Web API + getting process ID for shutting down later
        run: cd api && dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
        env:
          dbconnectionstring: ${{secrets.PGCONN}}

      - name: Run tests once API is running (sleep interval set to 60 seconds)
        run: cd Tests/apitests && sleep 60 && dotnet test
        env:
          dbconnectionstring: ${{secrets.PGCONN}}
          
      - name: Shutdown Web API once the tests are done running
        run: kill $API_PID
