on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  RepositoryTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      - name: Build and run Web API + getting process ID for shutting down later
        run: cd api && dotnet run & echo $! > api_pid.txt
        env:
          IsTestMode: ${{secrets.ISTESTMODE}}
          dbconnectionstring: ${{secrets.PGCONN}}

      - name: Run tests once API is running (sleep interval set to 60 seconds)
        run: cd TestProject && sleep 60 && dotnet test --filter FullyQualifiedName~TestProject.RepoTesting
        env:
          IsTestMode: ${{secrets.ISTESTMODE}}
          dbconnectionstring: ${{secrets.PGCONN}}
          
      - name: Shutdown Web API once the tests are done running
        run: kill $(cat api_pid.txt)
